### ISSUE TITLE
Fixed price not applied at the correct time

### ISSUE THREAD

**Issue by rvetrsek** [UtilitechAS/amsreader-firmware#1068]
**Describe the bug**
Fixed price not applied at the correct time.

**To Reproduce**
Timezone: Europe/Ljubljana
Fixed price for all days and hours, like in the screenshot.
Notice that the time is 12:18 (noon), and the Future energy price graph shows night prices (MT).

Future energy price graph:
<img width="1540" height="912" alt="Image" src="https://github.com/user-attachments/assets/4b9162f5-359a-4193-897b-74cdbc05af14" />

Fixed price settings:
<img width="1529" height="501" alt="Image" src="https://github.com/user-attachments/assets/843eb03d-9810-4a8d-bc8a-5495c4e8aa14" />

**Expected behavior**
Correct price applied to the current time.

**Hardware information:**
 - Country: Slovenia
 - Meter: Iskra AM550
 - Encryption enabled: Yes
 - AMS reader: Slimmelezer (esp8266)

**Relevant firmware information:**
 - Version: v2.5.0-rc3
 - MQTT: yes
 - MQTT payload type: HA

**Comment by ArnieO** [comment]
Huh. 
Looks like a bug that @gskjold must look into.

**Comment by gskjold** [comment]
This is weird, but I think there may be some problems defining several "fixed price". Could you instead add a row before this which is fixed with 0 value and the others as "+". This could help identify the issue. Should look something like my setup, only with 0 on the first row:

<img width="2042" height="670" alt="Image" src="https://github.com/user-attachments/assets/55cbd920-694a-45f0-ab97-71998d103d63" />

**Comment by gskjold** [comment]
Also, could you do a config file export where only "Price API" is ticked, this will give me your price config that I can use during debugging.

<img width="402" height="374" alt="Image" src="https://github.com/user-attachments/assets/2b7e0322-623e-4905-bd91-bb79724a43b7" />

**Comment by rvetrsek** [comment]
I tried your suggestion, but the problem persists. I did, however, need to set the fixed value to 0.0001, as it does not allow a zero value.

<img width="1273" height="794" alt="Image" src="https://github.com/user-attachments/assets/4eb43dbc-47e9-49ad-b828-9be1507abde9" />

<img width="1279" height="283" alt="Image" src="https://github.com/user-attachments/assets/77858f60-d36f-48b8-9269-4a6a6a20a68c" />


### This is my price config (without the hack):
```
amsconfig
version v2.5.0-rc3
boardType 100
priceEnabled 0
priceArea 10YSI-ELES-----O
priceCurrency EUR
priceModifier 0 "VT" import fixed 0.1199 mo,tu,we,th,fr 06,07,08,09,10,11,12,13,14,15,16,17,18,19,20,21 00-00 00-00
priceModifier 1 "MT" import fixed 0.0979 mo,tu,we,th,fr 00,01,02,03,04,05,22,23 00-00 00-00
priceModifier 2 "MT weekend" import fixed 0.0979 sa,su all 00-00 00-00
priceModifier 3 "VAT" import percent 22.0000 all all 00-00 00-00
dayplot 6 1764082800 20226.550 0 0 0 0 0 0 0 0 0 0 0 0 0 0 968 526 0 0 0 0 0 0 0 0 0 0.292 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
monthplot 7 1764068400 20223.957 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.292 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
energyaccounting 7 11 2.94 1.90 43.13 0.00 0.00 0.00 25 14 0.97 0 0 0.00 0 0 0.00 0 0 0.00 0 0 0.00 0.00 0.00
```

**Comment by rvetrsek** [comment]
Update: It seems to have fixed itself overnight. I initially set up the pricing yesterday, and now today, the future price graph is showing correctly, as is the current price in the Import gauge. So the issue might only be when you initially set up the price modifiers.

<img width="1279" height="281" alt="Image" src="https://github.com/user-attachments/assets/c4efef9e-6bfd-4723-8afa-2330e48aabfa" />

**Comment by gskjold** [comment]
Thanks for that input, will investigate

**Comment by gskjold** [comment]
It does have a issue with the hours the fixed price are applied to. Will be fixed for the final release
